//
// Created by vinsentli@tencent.com on 2024/6/13.
//

#pragma once

//add by vinsentli begin >>>>>>>>>

#define         VK_ERROR_UNKNOWN -13
#define         VK_ERROR_FRAGMENTATION  -1000161000
#define         VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS  -1000257000
#define         VK_PIPELINE_COMPILE_REQUIRED  1000297000
#define         VK_THREAD_IDLE_KHR  1000268000
#define         VK_THREAD_DONE_KHR  1000268001
#define         VK_OPERATION_DEFERRED_KHR  1000268002
#define         VK_OPERATION_NOT_DEFERRED_KHR  1000268003
#define  VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT                              0x00000002

#define VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR                           VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT
#define VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES      VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES_KHR
#define VkPhysicalDeviceShaderFloat16Int8Features                           VkPhysicalDeviceShaderFloat16Int8FeaturesKHR
#define VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2                          VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2_KHR
#define VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_KHR                       VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_EXT

#define VkDescriptorBindingFlags VkDescriptorBindingFlagsEXT
#define VkAttachmentDescription2 VkAttachmentDescription
#define VkAttachmentReference2 VkAttachmentReference
#define VkBufferDeviceAddressInfo VkBufferDeviceAddressInfoEXT

#define VK_KHR_SHADER_NON_SEMANTIC_INFO_EXTENSION_NAME "VK_KHR_shader_non_semantic_info"
#define VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME "VK_KHR_buffer_device_address"

#define VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO_KHR VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO_EXT
#define vkGetBufferDeviceAddressKHR vkGetBufferDeviceAddressEXT
#define VK_INDEX_TYPE_NONE_KHR VK_INDEX_TYPE_NONE_NV
#define VK_ERROR_NOT_PERMITTED_KHR VK_ERROR_NOT_PERMITTED_EXT
#define VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2 VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2_KHR
#define VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT
#define VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT
#define VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT
#define VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT_EXT

//add by vinsentli end <<<<<<<<<
